apiVersion: batch/v1
kind: CronJob
metadata:
  name: tvs-scheduler-cron
spec:
  # 台北時間 每天 15 16 17 18 點各執行一次
  schedule: "0 15,16,17,18 * * *"
  timeZone: "Asia/Taipei"
  jobTemplate:
    spec:
      # 執行完成後 86400 秒 自動刪除此 Job 與相關 Pod
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          containers:
          - name: tvs-scheduler
            image: asia-east1-docker.pkg.dev/twvixstock/tvs-repo/tvs-scheduler
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: tvs-config
            env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tvs-secret
                  key: DB_PASSWORD
            - name: CRAWLER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tvs-secret
                  key: CRAWLER_TOKEN
          # 執行完後自動關閉，不要重啟
          restartPolicy: OnFailure