server:
  Port: 8080
  Mode: "debug"

database:
  Host: "127.0.0.1"
  Port: 3306

crawler:
  BaseURL: "https://999.no.use"
  IntervalHour: 999
  GeminiModel: "gemini-3-flash-preview"
  GeminiModellite: "gemini-3.1-flash-lite-preview"